/**
 * Todo API
 * API documentation for Todo management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("TodosApi", () => {
  let instance: api.TodosApi
  beforeEach(function() {
    instance = new api.TodosApi(config)
  });

  test("deleteTodo", () => {
    const id: number = 56
    return expect(instance.deleteTodo(id, {})).resolves.toBe(null)
  })
  test("getTodoById", () => {
    const id: number = 56
    return expect(instance.getTodoById(id, {})).resolves.toBe(null)
  })
  test("getTodosList", () => {
    return expect(instance.getTodosList({})).resolves.toBe(null)
  })
  test("storeTodo", () => {
    const body: api.ApiTodosBody = undefined
    return expect(instance.storeTodo(body, {})).resolves.toBe(null)
  })
  test("updateTodo", () => {
    const body: api.TodosIdBody = undefined
    const id: number = 56
    return expect(instance.updateTodo(body, id, {})).resolves.toBe(null)
  })
})

