/*
 * Todo API
 * API documentation for Todo management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ApiTodosBody;
import io.swagger.client.model.Todo;
import io.swagger.client.model.TodosIdBody;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for TodosApi
 */
@Ignore
public class TodosApiTest {

    private final TodosApi api = new TodosApi();

    /**
     * Delete a todo
     *
     * Deletes a specific todo
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteTodoTest() throws Exception {
        Integer id = null;
        api.deleteTodo(id);

        // TODO: test validations
    }
    /**
     * Get a specific todo
     *
     * Returns a single todo
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTodoByIdTest() throws Exception {
        Integer id = null;
        Todo response = api.getTodoById(id);

        // TODO: test validations
    }
    /**
     * Get list of todos
     *
     * Returns a list of todos
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTodosListTest() throws Exception {
        List<Todo> response = api.getTodosList();

        // TODO: test validations
    }
    /**
     * Create a new todo
     *
     * Stores a new todo in the database
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void storeTodoTest() throws Exception {
        ApiTodosBody body = null;
        Todo response = api.storeTodo(body);

        // TODO: test validations
    }
    /**
     * Update a todo
     *
     * Updates an existing todo
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateTodoTest() throws Exception {
        TodosIdBody body = null;
        Integer id = null;
        Todo response = api.updateTodo(body, id);

        // TODO: test validations
    }
}
