/*
 * Todo API
 * API documentation for Todo management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.47
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ApiTodosBody model module.
 * @module model/ApiTodosBody
 * @version 1.0.0
 */
export class ApiTodosBody {
  /**
   * Constructs a new <code>ApiTodosBody</code>.
   * @alias module:model/ApiTodosBody
   * @class
   * @param title {String} 
   */
  constructor(title) {
    this.title = title;
  }

  /**
   * Constructs a <code>ApiTodosBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiTodosBody} obj Optional instance to populate.
   * @return {module:model/ApiTodosBody} The populated <code>ApiTodosBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ApiTodosBody();
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} title
 */
ApiTodosBody.prototype.title = undefined;

/**
 * @member {String} description
 */
ApiTodosBody.prototype.description = undefined;

