/*
 * Todo API
 * API documentation for Todo management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.47
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Todo model module.
 * @module model/Todo
 * @version 1.0.0
 */
export class Todo {
  /**
   * Constructs a new <code>Todo</code>.
   * @alias module:model/Todo
   * @class
   * @param title {String} 
   */
  constructor(title) {
    this.title = title;
  }

  /**
   * Constructs a <code>Todo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Todo} obj Optional instance to populate.
   * @return {module:model/Todo} The populated <code>Todo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Todo();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'Date');
      if (data.hasOwnProperty('updated_at'))
        obj.updatedAt = ApiClient.convertToType(data['updated_at'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Todo.prototype.id = undefined;

/**
 * @member {String} title
 */
Todo.prototype.title = undefined;

/**
 * @member {String} description
 */
Todo.prototype.description = undefined;

/**
 * @member {Date} createdAt
 */
Todo.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
Todo.prototype.updatedAt = undefined;

