/*
 * Todo API
 * API documentation for Todo management
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.47
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {ApiTodosBody} from './model/ApiTodosBody';
import {Todo} from './model/Todo';
import {TodosIdBody} from './model/TodosIdBody';
import {TodosApi} from './api/TodosApi';

/**
* API_documentation_for_Todo_management.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TodoApi = require('index'); // See note below*.
* var xxxSvc = new TodoApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TodoApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TodoApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TodoApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApiTodosBody model constructor.
     * @property {module:model/ApiTodosBody}
     */
    ApiTodosBody,

    /**
     * The Todo model constructor.
     * @property {module:model/Todo}
     */
    Todo,

    /**
     * The TodosIdBody model constructor.
     * @property {module:model/TodosIdBody}
     */
    TodosIdBody,

    /**
    * The TodosApi service constructor.
    * @property {module:api/TodosApi}
    */
    TodosApi
};
