//
// ApiTodosBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ApiTodosBody: Codable {

    public var title: String
    public var _description: String?

    public init(title: String, _description: String? = nil) {
        self.title = title
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case title
        case _description = "description"
    }

}
